### PR TITLE
Gix changes (for review only!)

### PR DESCRIPTION
**Pull request by gregorleban**
- several changes to the gix in order to speed it up for adding but mostly for deleting items from it
- added various methods to support byte fields in stores (TRecCmpByFieldByte, GetFieldNmByte, ...)

NOTE: the code is for review only - not to be merged yet!

### CODE REVIEW

**Comment by bergloman** [comment]
Seems fine to me - I presume you also performed **a ton** of tests :smiley:

**Comment by bergloman** [comment]
Seems fine to me

**Comment by blazf** [comment]
shall we merge?

**Comment by bergloman** [comment]
Do we feel lucky? :)
Fortuna audaces iuvat

**Comment by gregorleban** [comment]
let me fix the tabs first - somehow they sneaked in

**Comment by gregorleban** [comment]
A question: I set the main new parameter in TGix CanFirstChildBeUnfilled as false which will make gix work as it did in the past - also meaning slow deletes. Should I leave it false and we then in TIndex add option to set it to true or should I set it to true by default in TGix?

**Comment by blazf** [comment]
I would set it to `true` by default, since FIFO is the default mode of adding and deleting things from `TGix` in the current QMiner.

**Comment by gregorleban** [comment]
made last changes, should be fine to merge

**Pull request merged**
